image: node:lts

pipelines:
  default:
    - step:
        name: Install
        caches:
          - node
        script:
          - yarn
    - step:
        name: Build
        caches:
          - node
        script:
          - yarn build
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn test:ci
          - yarn test:coverage:badges
          - pipe: docker://bitbucketpipelines/bitbucket-upload-file:0.1.0
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              FILENAME: 'coverage/badge.svg'
        artifacts:
          - coverage/**
